site_name: OpenManus‑Stack
nav:
  - Home: index.md
  - API: api.md
  - Admin Guide: admin-guide.md
  - Developer Guide: developer-guide.md
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true